/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "volcano.sh/apis/pkg/apis/batch/v1alpha1"
	batchv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/batch/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// HyperJobsGetter has a method to return a HyperJobInterface.
// A group's client should implement this interface.
type HyperJobsGetter interface {
	HyperJobs(namespace string) HyperJobInterface
}

// HyperJobInterface has methods to work with HyperJob resources.
type HyperJobInterface interface {
	Create(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.CreateOptions) (*v1alpha1.HyperJob, error)
	Update(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (*v1alpha1.HyperJob, error)
	UpdateStatus(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (*v1alpha1.HyperJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HyperJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HyperJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperJob, err error)
	Apply(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error)
	ApplyStatus(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error)
	HyperJobExpansion
}

// hyperJobs implements HyperJobInterface
type hyperJobs struct {
	client rest.Interface
	ns     string
}

// newHyperJobs returns a HyperJobs
func newHyperJobs(c *BatchV1alpha1Client, namespace string) *hyperJobs {
	return &hyperJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hyperJob, and returns the corresponding hyperJob object, and an error if there is any.
func (c *hyperJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HyperJob, err error) {
	result = &v1alpha1.HyperJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HyperJobs that match those selectors.
func (c *hyperJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HyperJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HyperJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hyperJobs.
func (c *hyperJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hyperjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hyperJob and creates it.  Returns the server's representation of the hyperJob, and an error, if there is any.
func (c *hyperJobs) Create(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.CreateOptions) (result *v1alpha1.HyperJob, err error) {
	result = &v1alpha1.HyperJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hyperjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hyperJob and updates it. Returns the server's representation of the hyperJob, and an error, if there is any.
func (c *hyperJobs) Update(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (result *v1alpha1.HyperJob, err error) {
	result = &v1alpha1.HyperJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(hyperJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *hyperJobs) UpdateStatus(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (result *v1alpha1.HyperJob, err error) {
	result = &v1alpha1.HyperJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(hyperJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hyperJob and deletes it. Returns an error if one occurs.
func (c *hyperJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hyperJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hyperJob.
func (c *hyperJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperJob, err error) {
	result = &v1alpha1.HyperJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied hyperJob.
func (c *hyperJobs) Apply(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error) {
	if hyperJob == nil {
		return nil, fmt.Errorf("hyperJob provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(hyperJob)
	if err != nil {
		return nil, err
	}
	name := hyperJob.Name
	if name == nil {
		return nil, fmt.Errorf("hyperJob.Name must be provided to Apply")
	}
	result = &v1alpha1.HyperJob{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *hyperJobs) ApplyStatus(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error) {
	if hyperJob == nil {
		return nil, fmt.Errorf("hyperJob provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(hyperJob)
	if err != nil {
		return nil, err
	}

	name := hyperJob.Name
	if name == nil {
		return nil, fmt.Errorf("hyperJob.Name must be provided to Apply")
	}

	result = &v1alpha1.HyperJob{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("hyperjobs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
